import apache_beam as beam
from datetime import datetime
from apache_beam.options.pipeline_options import PipelineOptions

#gs://tnt01-odycda-bld-01-stb-eu-rawzone-52fd7181/thParty/MFVS/GFV/Monthly/Dummy_data/

CPRRVN_GFV_DATA_table_spec = "tnt01-odycda-bld-01-1681:tnt01_odycda_bqd_euwe2_pricing.CPRRVN-BHBaseNewGFV-20231127"


class CustomPipelineOptions (PipelineOptions):
    @classmethod
    def add_argparse_args(cls, parser):
        pass

CPRRVN_Data_schema = {
    'fields' : [{'name': 'Cap_Code', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'Cap_Id', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'Reg_Year', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'Reg_Letter', 'type': 'STRING', 'mode': 'NULLABLE'},
                {'name': 'Mileagel', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M1_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage2', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2 T12 GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2 T18 GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M2_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage3', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_172_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M3_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage4', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4 T48 GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4 T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4 T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4_178_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M4_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage5', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M5_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M5_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M5_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M5_T24 GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M5 T30 GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M5 T36 GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M5_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'MS_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'MS_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M5_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M5_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'MS_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'MS_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M5_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage6', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M6_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage7', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M7_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage8', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M8_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage9', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M9_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage10', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M10_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileagell', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_172_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M11_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage12', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M12_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage13', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M13_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage14', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M14_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage15', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M15_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage16', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M16_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage17', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M17_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage18', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M18_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage19', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M19_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'Mileage20', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T6_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T12_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T18_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T24_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T30_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T36_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T42_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T48_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T54_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T60_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T66_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T72_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T78_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'M20_T84_GFV', 'type': 'INTEGER', 'mode': 'NULLABLE'},
                {'name': 'New_Price', 'type': 'INTEGER', 'mode': 'NULLABLE'}
    ]
}


def convert_key_val_gfvnew(element):
    keys = []
    values = [ele for ele in element]
    dict_val = {keys:values for (keys,values) in zip(keys,values)}
    return dict_val

def run(project_id, bq_dataset, bucket_name, base_path, file_name):
    pipeline_options = beam.options.pipeline_options.PipelineOptions(
        project=project_id,
        runner="DirectRunner",
        job_name="newcar",
        temp_location='gs://tnt01-odycda-bld-01-stb-eu-rawzone-52fd7181/thParty/MFVS/GFV/Monthly/dataflow/temp',
        region='europe-west2',
        staging_location='gs://tnt01-odycda-bld-01-stb-eu-rawzone-52fd7181/thParty/MFVS/GFV/Monthly/staging',
        service_account_email='svc-dfl-user@tnt01-odycda-bld-01-1681.iam.gserviceaccount.com',
        dataflow_kms_key='projects/tnt01-odykms-bld-01-35d7/locations/europe-west2/keyRings/krs-kms-tnt01-euwe2-cdp/cryptoKeys/keyhsm-kms-tnt01-euwe2-cdp',
        subnetwork='https://www.googleapis.com/compute/v1/projects/tnt01-hst-bld-e88h/regions/europe-west2/subnetworks/odycda-csn-euwe2-kc1-01-bld-01',
        num_workers=1,
        max_num_workers=4,
        use_public_ips=False,
        autoscaling_algorithm='THROUGHPUT_BASED',
        save_main_session=True
    )

    with beam.Pipeline(options=pipeline_options) as pipe:
        merged_file_read = (
            pipe | "Reading the Merged file data" >> beam.io.ReadFromText(f"gs://{bucket_name}/{base_path}/{file_name}", skip_header_lines=1)
                 | "Splitting the data into computational units" >> beam.Map(lambda x: x.split(","))
                 | "Formatting column into key value pair" >> beam.Map(convert_key_val_gfvnew)
                 | beam.Map(print)  # Temporary printing, replace with desired processing
                 | "Pushing the Gfv data to bigquery">>beam.io.WriteToBigQuery(table=CPRRVN_GFV_DATA_table_spec, schema=CPRRVN_Data_schema, create_disposition=beam.io.BigQueryDisposition.CREATE_IF_NEEDED, write_disposition=beam.io.BigQueryDisposition.WRITE_TRUNCATE) )

if __name__ == '_main__':
    project_id = 'tnt01-odycda-bld-01-1b81'
    bq_dataset='tnt01_odycda_bqd_euwe2_pricing'
    bucket_name = "tnt01-odycda-bld-01-stb-eu-rawzone-52fd7181"
    base_path = "thParty/MFVS/GFV/Monthly/Dummy_data"
    file_name = "CPRRVN-BHBaseNewGFV-20231127.csv"

def transform():

    print("****** **********Big Query CPRRVN Table loading process started*****************")

    run(project_id, bq_dataset, bucket_name, base_path, file_name)

    print("************ *************Big Query CPRRVN Table loading process complete******************")

transform()


